import { StyleSheet } from "react-native";
import { IrisColors, IrisFonts } from "@/constants/theme";
export const styles = StyleSheet.create({
  page: {
    alignItems: "center",
    backgroundColor: IrisColors.opticalBlack,
    flex: 1,
  },
  safeArea: {
    flex: 1,
    width: "100%",
  },
  appShell: {
    alignSelf: "center",
    backgroundColor: IrisColors.opticalBlack,
    flex: 1,
    maxWidth: 520,
    overflow: "hidden",
    width: "100%",
  },
  nonInteractive: {
    pointerEvents: "none",
  },
  topRail: {
    alignItems: "center",
    flexDirection: "row",
    height: 58,
    justifyContent: "space-between",
    paddingHorizontal: 18,
  },
  brandLockup: {
    alignItems: "center",
    flexDirection: "row",
    gap: 9,
  },
  wordmark: {
    color: IrisColors.chalk,
    fontFamily: IrisFonts.displaySemiBold,
    fontSize: 22,
    letterSpacing: 4,
  },
  sessionState: {
    alignItems: "center",
    flexDirection: "row",
    gap: 6,
    position: "absolute",
    left: "50%",
    transform: [{ translateX: -25 }],
  },
  liveDot: {
    backgroundColor: IrisColors.chalk,
    borderRadius: 4,
    height: 7,
    width: 7,
  },
  sessionText: {
    color: IrisColors.fog,
    fontFamily: IrisFonts.displayMedium,
    fontSize: 11,
    letterSpacing: 1.4,
  },
  counterPill: {
    alignItems: "flex-end",
  },
  counterText: {
    color: IrisColors.chalk,
    fontFamily: IrisFonts.displaySemiBold,
    fontSize: 18,
    lineHeight: 18,
  },
  counterLabel: {
    color: IrisColors.fog,
    fontFamily: IrisFonts.displayMedium,
    fontSize: 8,
    letterSpacing: 1.4,
  },
  viewfinder: {
    backgroundColor: "#24201E",
    flex: 1,
    minHeight: 260,
    overflow: "hidden",
    position: "relative",
  },
  sceneGlow: {
    backgroundColor: "#96938C",
    borderRadius: 180,
    height: 360,
    opacity: 0.46,
    position: "absolute",
    right: -100,
    top: -95,
    width: 360,
  },
  sceneOrb: {
    backgroundColor: "#6F6E6A",
    borderColor: "#AEACA5",
    borderRadius: 90,
    borderWidth: 2,
    height: 180,
    opacity: 0.72,
    position: "absolute",
    right: 38,
    top: 70,
    width: 180,
  },
  sceneColumn: {
    backgroundColor: "#151517",
    bottom: -34,
    height: "86%",
    left: 26,
    position: "absolute",
    transform: [{ rotate: "-8deg" }],
    width: "24%",
  },
  scenePlane: {
    backgroundColor: "#65635D",
    bottom: 22,
    height: "37%",
    left: "23%",
    opacity: 0.9,
    position: "absolute",
    transform: [{ rotate: "7deg" }],
    width: "88%",
  },
  sceneShadow: {
    backgroundColor: "#0A0A0B",
    bottom: -105,
    borderRadius: 240,
    height: 250,
    left: -30,
    opacity: 0.64,
    position: "absolute",
    width: "120%",
  },
  gridLineVertical: {
    backgroundColor: "rgba(244,242,237,0.2)",
    bottom: 0,
    position: "absolute",
    top: 0,
    width: StyleSheet.hairlineWidth,
  },
  gridLineHorizontal: {
    backgroundColor: "rgba(244,242,237,0.2)",
    height: StyleSheet.hairlineWidth,
    left: 0,
    position: "absolute",
    right: 0,
  },
  exposureChip: {
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: "rgba(5,5,6,0.72)",
    borderColor: "rgba(244,242,237,0.14)",
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: "row",
    gap: 9,
    paddingHorizontal: 13,
    paddingVertical: 7,
    position: "absolute",
    top: 14,
  },
  exposureText: {
    color: IrisColors.chalk,
    fontFamily: IrisFonts.displayMedium,
    fontSize: 13,
    letterSpacing: 0.8,
  },
  exposureDivider: {
    backgroundColor: IrisColors.fog,
    height: 10,
    width: 1,
  },
  focusReticle: {
    alignItems: "center",
    borderColor: IrisColors.chalk,
    borderRadius: 8,
    borderWidth: 1.5,
    height: 46,
    justifyContent: "center",
    marginLeft: -23,
    marginTop: -23,
    position: "absolute",
    width: 46,
  },
  focusDot: {
    backgroundColor: IrisColors.chalk,
    borderRadius: 2,
    height: 4,
    width: 4,
  },
  previewLabel: {
    alignItems: "center",
    flexDirection: "row",
    gap: 6,
    left: 13,
    position: "absolute",
    top: 14,
  },
  previewLabelDot: {
    backgroundColor: IrisColors.chalk,
    borderRadius: 3,
    height: 5,
    width: 5,
  },
  previewLabelText: {
    color: IrisColors.chalk,
    fontFamily: IrisFonts.displayMedium,
    fontSize: 9,
    letterSpacing: 1.4,
  },
  reviewCloseButton: {
    alignItems: "center",
    backgroundColor: "rgba(5,5,6,0.82)",
    borderColor: "rgba(244,242,237,0.2)",
    borderCurve: "continuous",
    borderRadius: 16,
    borderWidth: 1,
    minHeight: 44,
    paddingHorizontal: 15,
    position: "absolute",
    right: 13,
    top: 9,
    justifyContent: "center",
  },
  reviewCloseText: {
    color: IrisColors.chalk,
    fontFamily: IrisFonts.displaySemiBold,
    fontSize: 10,
    letterSpacing: 1.1,
  },
  lensRail: {
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: "rgba(5,5,6,0.78)",
    borderColor: "rgba(244,242,237,0.13)",
    borderRadius: 22,
    borderWidth: 1,
    bottom: 14,
    flexDirection: "row",
    gap: 2,
    padding: 4,
    position: "absolute",
  },
  lensButton: {
    alignItems: "center",
    borderRadius: 17,
    height: 34,
    justifyContent: "center",
    width: 40,
  },
  lensButtonSelected: {
    backgroundColor: IrisColors.chalk,
  },
  lensText: {
    color: IrisColors.fog,
    fontFamily: IrisFonts.displaySemiBold,
    fontSize: 14,
  },
  lensTextSelected: {
    color: IrisColors.opticalBlack,
  },
  millimeterLabel: {
    color: IrisColors.fog,
    fontFamily: IrisFonts.displayMedium,
    fontSize: 8,
    marginHorizontal: 7,
  },
  captureFlash: {
    ...StyleSheet.absoluteFill,
    backgroundColor: IrisColors.chalk,
    opacity: 0.78,
  },
  controlDeck: {
    backgroundColor: IrisColors.carbon,
    borderColor: IrisColors.line,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    borderTopWidth: 1,
    marginTop: -1,
    paddingBottom: 4,
    paddingHorizontal: 14,
  },
  errorBanner: {
    backgroundColor: "rgba(242,13,47,0.14)",
    borderColor: "rgba(242,13,47,0.4)",
    borderCurve: "continuous",
    borderRadius: 12,
    borderWidth: 1,
    marginTop: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  errorText: {
    color: IrisColors.chalk,
    fontSize: 13,
    lineHeight: 18,
    textAlign: "center",
  },
  modeTabs: {
    alignItems: "stretch",
    backgroundColor: IrisColors.ink,
    borderRadius: 22,
    flexDirection: "row",
    height: 54,
    marginTop: 8,
  },
  modeTab: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    position: "relative",
  },
  modeText: {
    color: IrisColors.fog,
    fontFamily: IrisFonts.displaySemiBold,
    fontSize: 16,
    letterSpacing: 1.8,
  },
  modeTextSelected: {
    color: IrisColors.chalk,
  },
  modeRule: {
    backgroundColor: IrisColors.signalRed,
    borderRadius: 1,
    bottom: 7,
    height: 2,
    position: "absolute",
    width: 34,
  },
  toolGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    justifyContent: "space-between",
    marginTop: 8,
  },
  tool: {
    alignItems: "center",
    borderColor: IrisColors.line,
    borderRadius: 14,
    borderWidth: 1,
    flexBasis: "22%",
    flexGrow: 1,
    justifyContent: "center",
    minHeight: 54,
    minWidth: 0,
    paddingHorizontal: 3,
    paddingVertical: 6,
  },
  toolActive: {
    backgroundColor: IrisColors.graphite,
    borderColor: "rgba(244,242,237,0.2)",
  },
  toolPressed: {
    backgroundColor: "#303034",
    transform: [{ scale: 0.97 }],
  },
  toolValue: {
    color: IrisColors.chalk,
    fontFamily: IrisFonts.displaySemiBold,
    fontSize: 12,
    marginTop: 5,
  },
  toolLabel: {
    color: IrisColors.fog,
    fontFamily: IrisFonts.displayMedium,
    fontSize: 8,
    letterSpacing: 0.6,
    marginTop: 1,
  },
  symbolFallback: {
    color: IrisColors.chalk,
    fontFamily: IrisFonts.displayMedium,
    fontSize: 18,
  },
  captureRail: {
    alignItems: "center",
    flexDirection: "row",
    height: 72,
    justifyContent: "space-between",
    paddingHorizontal: 6,
    position: "relative",
  },
  lookControl: {
    alignItems: "center",
    flexDirection: "row",
    gap: 9,
    minWidth: 104,
  },
  lookSwatch: {
    backgroundColor: "#8E8D88",
    borderColor: IrisColors.chalk,
    borderRadius: 11,
    borderWidth: 1,
    height: 30,
    overflow: "hidden",
    width: 24,
  },
  lookLabel: {
    color: IrisColors.fog,
    fontFamily: IrisFonts.displayMedium,
    fontSize: 8,
    letterSpacing: 1.1,
  },
  lookValue: {
    color: IrisColors.chalk,
    fontFamily: IrisFonts.displaySemiBold,
    fontSize: 13,
  },
  shutterOuter: {
    alignItems: "center",
    borderColor: IrisColors.chalk,
    borderRadius: 30,
    borderWidth: 2,
    height: 60,
    justifyContent: "center",
    left: "50%",
    marginLeft: -30,
    position: "absolute",
    width: 60,
  },
  shutterInner: {
    backgroundColor: IrisColors.chalk,
    borderRadius: 24,
    height: 48,
    width: 48,
  },
  shutterPressed: {
    borderColor: IrisColors.fog,
    transform: [{ scale: 0.94 }],
  },
  shutterDisabled: {
    opacity: 0.38,
  },
  flipButton: {
    alignItems: "center",
    backgroundColor: IrisColors.graphite,
    borderColor: IrisColors.line,
    borderRadius: 22,
    borderWidth: 1,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  pressed: {
    opacity: 0.64,
  },
});
